# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44c8b4c78a75f25d324539fa7b9a237e3a7b6646bdc72e6211c257ef9cbd5efea3eead244295a31904c1c6c3b9275963e4890cdf75330681a53ae999af4f5099

test:
  secret_key_base: 597455b871a1cbbeb940f797714e525cd59c9e6bee35a1df6b00f643a21d1fbe19d1f6368e8586d936d4dc415200e89adcea4a2bc301bf2bd96df7f01658959a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
